-- CRM de vendas do SaaS (item 24, parte 3). Diferente de leads_cfp
-- (referencia estatica raspada do CFP, sem RLS) -- aqui e dado
-- comercial de pipeline de vendas, admin-only de verdade via RLS.
create table "Lead" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  nome text not null,
  telefone text,
  email text,
  usuario_id bigint references "Usuarios"(id),
  visitante_sessao_id uuid,
  estagio text not null default 'novo'
    check (estagio in ('novo', 'em_contato', 'qualificado', 'proposta_enviada', 'fechado_ganho', 'perdido')),
  origem text not null default 'manual' check (origem in ('cadastro', 'manual'))
);

create table "LeadNota" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id bigint not null references "Lead"(id) on delete cascade,
  texto text not null
);

alter table "Lead" enable row level security;
alter table "LeadNota" enable row level security;

create policy "lead_admin_all" on "Lead"
  for all using (public.is_admin()) with check (public.is_admin());
create policy "leadnota_admin_all" on "LeadNota"
  for all using (public.is_admin()) with check (public.is_admin());
