alter table "Usuarios"
  add column carne_leao_frequencia text check (carne_leao_frequencia in ('semanal', 'quinzenal', 'mensal')),
  add column carne_leao_email text,
  add column carne_leao_ultimo_envio date;

create table "EnvioAutomaticoCarneLeao" (
  id bigint generated by default as identity primary key,
  usuario bigint not null references "Usuarios"(id),
  executado_em timestamptz not null default now(),
  sucesso boolean not null,
  mensagem_erro text,
  quantidade_linhas int not null default 0
);
