-- Recebimento substitui PagamentoSessao: um recebimento pode cobrir
-- multiplas sessoes (RecebimentoSessao, uma linha por sessao alocada) ou
-- nenhuma ainda (credito antecipado — saldo = valor_total menos a soma
-- dos valor_aplicado ja lancados). O LancamentoFinanceiro (Receita) e
-- criado junto com o Recebimento, no valor total, independente de ja
-- haver sessao alocada.
create table "Recebimento" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  paciente bigint not null references "Paciente"(id),
  responsavel_financeiro bigint not null references "ResponsavelFinanceiro"(id),
  data_recebimento date not null,
  valor_total numeric not null check (valor_total > 0),
  forma_pagamento text not null check (forma_pagamento in ('Dinheiro', 'Pix', 'Cartão')),
  conta bigint not null references "ContaFinanceira"(id),
  lancamento bigint not null references "LancamentoFinanceiro"(id),
  owner uuid not null default auth.uid()
);

create table "RecebimentoSessao" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  recebimento bigint not null references "Recebimento"(id),
  sessao bigint not null references "Sessao"(id),
  valor_aplicado numeric not null check (valor_aplicado > 0),
  owner uuid not null default auth.uid(),
  unique (recebimento, sessao)
);

alter table "Recebimento" enable row level security;
alter table "RecebimentoSessao" enable row level security;

create policy "recebimento_select_own" on "Recebimento"
  for select using (owner = auth.uid() or public.is_admin());
create policy "recebimento_insert_own" on "Recebimento"
  for insert with check (owner = auth.uid());
create policy "recebimento_update_own" on "Recebimento"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "recebimento_delete_own" on "Recebimento"
  for delete using (owner = auth.uid() or public.is_admin());

create policy "recebimentosessao_select_own" on "RecebimentoSessao"
  for select using (owner = auth.uid() or public.is_admin());
create policy "recebimentosessao_insert_own" on "RecebimentoSessao"
  for insert with check (owner = auth.uid());
create policy "recebimentosessao_update_own" on "RecebimentoSessao"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "recebimentosessao_delete_own" on "RecebimentoSessao"
  for delete using (owner = auth.uid() or public.is_admin());
