-- Dados fiscais do profissional (emitente da NFS-e) — 1 por profissional.
create table "DadosFiscaisProfissional" (
  id bigint generated by default as identity primary key,
  owner uuid not null unique default auth.uid() references auth.users(id),

  tipo_documento text not null check (tipo_documento in ('cpf', 'cnpj')),
  documento text not null,
  inscricao_municipal text,
  nome_empresarial text not null,
  email_nfse text not null,
  telefone_nfse text,
  logradouro text not null,
  numero text not null,
  complemento text,
  bairro text not null,
  municipio_ibge text not null,
  uf text not null,
  cep text not null,

  optante_simples_nacional int not null default 3
    check (optante_simples_nacional in (1, 2, 3)),
  regime_apuracao_sn int,

  codigo_tributacao_nacional text not null,

  certificado_pfx_cifrado text,
  certificado_senha_cifrada text,
  certificado_titular text,
  certificado_validade date,

  ambiente text not null default 'homologacao' check (ambiente in ('homologacao', 'producao')),
  serie text not null default '1',
  proximo_numero int not null default 1,

  created_at timestamptz not null default now()
);

-- Registro de cada emissao. pagamento_sessao (nao sessao/paciente direto):
-- o valor fiscal correto e o que foi de fato recebido (PagamentoSessao),
-- mesma fonte que o item 8 (Carne-Leao) ja usa -- ver spec.
create table "NotaFiscal" (
  id bigint generated by default as identity primary key,
  owner uuid not null default auth.uid() references auth.users(id),
  pagamento_sessao bigint not null unique references "PagamentoSessao"(id),

  status text not null default 'pendente'
    check (status in ('pendente', 'autorizada', 'rejeitada', 'cancelada')),
  ambiente text not null,
  numero int not null,
  serie text not null,
  dps_id text,
  chave_acesso text,
  xml_dps text,
  xml_nfse text,
  erros jsonb,

  created_at timestamptz not null default now()
);

alter table "DadosFiscaisProfissional" enable row level security;
alter table "NotaFiscal" enable row level security;

create policy "dadosfiscaisprofissional_select_own" on "DadosFiscaisProfissional"
  for select using (owner = auth.uid() or public.is_admin());
create policy "dadosfiscaisprofissional_insert_own" on "DadosFiscaisProfissional"
  for insert with check (owner = auth.uid());
create policy "dadosfiscaisprofissional_update_own" on "DadosFiscaisProfissional"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "dadosfiscaisprofissional_delete_own" on "DadosFiscaisProfissional"
  for delete using (owner = auth.uid() or public.is_admin());

create policy "notafiscal_select_own" on "NotaFiscal"
  for select using (owner = auth.uid() or public.is_admin());
create policy "notafiscal_insert_own" on "NotaFiscal"
  for insert with check (owner = auth.uid());
create policy "notafiscal_update_own" on "NotaFiscal"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "notafiscal_delete_own" on "NotaFiscal"
  for delete using (owner = auth.uid() or public.is_admin());

-- Trava a troca de ambiente: uma vez em producao, nunca mais volta pra
-- homologacao. Defesa em profundidade -- a Server Action ja evita isso,
-- mas o banco garante mesmo se algum caminho de codigo futuro esquecer.
create or replace function public.impedir_reversao_ambiente_nfse()
returns trigger
language plpgsql
as $$
begin
  if old.ambiente = 'producao' and new.ambiente <> 'producao' then
    raise exception 'Nao e possivel voltar de producao para homologacao.';
  end if;
  return new;
end;
$$;

create trigger trg_impedir_reversao_ambiente_nfse
  before update on "DadosFiscaisProfissional"
  for each row
  execute function public.impedir_reversao_ambiente_nfse();

-- Numeracao transacional: consome o proximo numero E grava a NotaFiscal
-- pendente na MESMA operacao (UPDATE...RETURNING trava a linha do
-- profissional, serializando emissoes concorrentes -- nunca um SELECT
-- seguido de UPDATE separado, que e o caminho da duplicata).
create or replace function public.registrar_nota_fiscal_pendente(p_pagamento_sessao bigint)
returns table (id bigint, numero int, serie text, ambiente text)
language plpgsql
as $$
declare
  v_numero int;
  v_serie text;
  v_ambiente text;
  v_id bigint;
begin
  update "DadosFiscaisProfissional" df
     set proximo_numero = df.proximo_numero + 1
   where df.owner = auth.uid()
  returning df.proximo_numero - 1, df.serie, df.ambiente into v_numero, v_serie, v_ambiente;

  if v_numero is null then
    raise exception 'Dados fiscais nao configurados para este profissional';
  end if;

  insert into "NotaFiscal" (owner, pagamento_sessao, status, ambiente, numero, serie)
  values (auth.uid(), p_pagamento_sessao, 'pendente', v_ambiente, v_numero, v_serie)
  returning "NotaFiscal".id into v_id;

  return query select v_id, v_numero, v_serie, v_ambiente;
end;
$$;
