-- Historico de reagendamentos de sessao, usado pela tool agent_reagendar_sessao
-- do agente de WhatsApp (item 13): cada reagendamento vira uma linha aqui, e
-- a contagem por paciente no mes corrente alimenta o alerta de "paciente
-- remarca com frequencia incomum".
create table "SessaoReagendamento" (
  id bigint generated by default as identity primary key,
  sessao bigint not null references "Sessao"(id) on delete cascade,
  paciente bigint not null references "Paciente"(id) on delete cascade,
  data_anterior date not null,
  horario_anterior time not null,
  data_nova date not null,
  horario_novo time not null,
  reagendado_em timestamptz not null default now()
);

create index sessaoreagendamento_paciente_idx on "SessaoReagendamento"(paciente, reagendado_em);

alter table "SessaoReagendamento" enable row level security;

-- mesmo padrao em cadeia do item 12 (AnamneseFollowup): sem coluna owner
-- direta, escopo via join ate Paciente.owner.
create policy "sessaoreagendamento_all_via_paciente" on "SessaoReagendamento"
  for all
  using (
    exists (
      select 1 from "Paciente" p
      where p.id = "SessaoReagendamento".paciente
        and (p.owner = auth.uid() or public.is_admin())
    )
  )
  with check (
    exists (
      select 1 from "Paciente" p
      where p.id = "SessaoReagendamento".paciente
        and (p.owner = auth.uid() or public.is_admin())
    )
  );
