-- Migration: suporte ao agente de WhatsApp
-- Reescrita com base no schema REAL do projeto (rohulajgyxdangxfurha), confirmado
-- via introspecção direta em 2026-07-27. Nomes de tabela em PascalCase e
-- precisam de aspas duplas; ids são bigint; ownership é feito via coluna
-- "owner" (uuid = auth.uid()), não por "consultorio_id" em toda tabela.

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- ============================================================
-- Vínculo do psicólogo ao WhatsApp (coluna nova e dedicada, não reaproveita
-- "Usuarios".contato)
-- ============================================================

alter table "Usuarios"
  add column if not exists whatsapp_number text,
  add column if not exists whatsapp_verified boolean not null default false;

create unique index if not exists usuarios_whatsapp_number_unique
  on "Usuarios" (whatsapp_number)
  where whatsapp_number is not null;

-- Códigos de verificação de 6 dígitos gerados no onboarding ("Vincular WhatsApp")
create table if not exists whatsapp_verificacao_codigos (
  id uuid primary key default gen_random_uuid(),
  usuario_id bigint not null references "Usuarios"(id) on delete cascade,
  whatsapp_number text not null,
  codigo text not null,
  expira_em timestamptz not null,
  usado boolean not null default false,
  criado_em timestamptz not null default now()
);

-- ============================================================
-- Estado de conversa (qual consultório está "ativo" quando há mais de um)
-- ============================================================

create table if not exists agent_sessions (
  whatsapp_number text primary key,
  usuario_id bigint references "Usuarios"(id) on delete cascade,
  consultorio_ativo_id bigint references "Consultorio"(id),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- Log de auditoria de toda ação do agente (essencial para disputas e LGPD)
-- ============================================================

create table if not exists agent_audit_log (
  id uuid primary key default gen_random_uuid(),
  whatsapp_number text not null,
  consultorio_id bigint references "Consultorio"(id),
  tool_name text not null,
  parametros jsonb,
  resultado jsonb,
  sucesso boolean not null default true,
  mensagem_erro text,
  criado_em timestamptz not null default now()
);

create index if not exists agent_audit_log_consultorio_idx
  on agent_audit_log (consultorio_id, criado_em desc);

-- ============================================================
-- Controle de lembretes proativos (evita duplicidade de envio)
-- ============================================================

create table if not exists lembretes_enviados (
  id uuid primary key default gen_random_uuid(),
  sessao_id bigint not null references "Sessao"(id) on delete cascade,
  tipo text not null check (tipo in ('lembrete_sessao', 'lembrete_pagamento')),
  enviado_em timestamptz not null default now(),
  unique (sessao_id, tipo)
);

-- Opt-in explícito do paciente para receber lembretes por WhatsApp (LGPD)
alter table "Paciente"
  add column if not exists whatsapp_lembrete_opt_in boolean not null default false;

-- ============================================================
-- Tabela nova: Recibo (não existia no schema real — necessária para a tool
-- agent_gerar_recibo e para a tela "Recibos" do PRD original)
-- ============================================================

create table if not exists "Recibo" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sessao bigint not null references "Sessao"(id),
  consultorio bigint not null references "Consultorio"(id),
  paciente bigint not null references "Paciente"(id),
  data_emissao date not null default current_date,
  owner uuid not null
);
