-- Rastreamento de pageview nos dominios publicos (home, comece, busca,
-- blog) + funil pre-login do dominio principal -- base pro CRM de
-- vendas (item 24 do backlog). Sem RLS com policy: so service_role
-- (que ignora RLS) le/escreve aqui, mesmo padrao ja usado em
-- "EventoAssinatura"/"EnvioAutomaticoCarneLeao".
create table "VisitaPagina" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sessao_id uuid not null,
  host text not null,
  path text not null,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  ip_hash text,
  user_agent text
);

create index visitapagina_sessao_id_idx on "VisitaPagina" (sessao_id);

alter table "VisitaPagina" enable row level security;

-- Liga um cadastro ao funil de visitas que levou a ele. Sem FK: sessao_id
-- nao e chave unica em VisitaPagina (varias linhas por sessao), o link e
-- so por igualdade de valor na hora da consulta.
alter table "Usuarios" add column visitante_sessao_id uuid;
