-- supabase/migrations/20260827000001_add_assinatura_usuarios.sql

alter table "Usuarios"
  add column plano_pago text check (plano_pago in ('gestao', 'gestao_marketing', 'marketing')),
  add column plano_pretendido text check (plano_pretendido in ('gratis', 'gestao', 'gestao_marketing', 'marketing')),
  add column plano_pretendido_a_partir_de timestamptz,
  add column assinatura_status text check (assinatura_status in ('ativa', 'inadimplente', 'cancelada')),
  add column asaas_customer_id text,
  add column asaas_subscription_id text,
  add column assinatura_vencida_em timestamptz;

alter table "Usuarios" drop constraint "Usuarios_plano_check";
alter table "Usuarios" add constraint "Usuarios_plano_check"
  check (plano in ('gratis', 'gestao', 'gestao_marketing', 'marketing'));

alter table "Usuarios" alter column plano set default 'gratis';

-- Fecha a lacuna: a policy "usuarios_self" e' row-level (for all, sem
-- restricao de coluna) -- sem isto, qualquer profissional logado
-- conseguiria setar o proprio plano/assinatura via uma chamada direta a
-- API REST do Supabase, sem passar pelo checkout do Asaas. So o
-- service_role (usado pelo webhook, pelo job diario, e pela acao de admin
-- corrigida na Task 2) pode escrever essas colunas.
--
-- Revoga UPDATE a nivel de tabela, depois concede apenas nas colunas permitidas
-- (nao funciona revogar coluna especifica quando existe grant a nivel de tabela)
revoke update on "Usuarios" from authenticated;
grant update (nome, cpf, crp, email, contato, whatsapp_number, whatsapp_verified, carne_leao_email, carne_leao_frequencia, carne_leao_ultimo_envio) on "Usuarios" to authenticated;

create table "EventoAssinatura" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  usuario bigint references "Usuarios"(id),
  asaas_event_id text not null unique,
  tipo text not null,
  payload jsonb not null,
  processado_com_sucesso boolean not null default true,
  mensagem_erro text
);

alter table "EventoAssinatura" enable row level security;
-- sem nenhuma policy: so service_role (que ignora RLS) le/escreve aqui,
-- mesmo padrao ja usado em "EnvioAutomaticoCarneLeao".
