-- Segmento "Anamnese" no cadastro do paciente (backlog item 12): dados
-- clinicos (medicacao, queixa inicial, historico etc.), separados dos
-- dados cadastrais/financeiros que ja existem em Paciente.
--
-- Anamnese guarda o estado ATUAL (1:1 com Paciente, criada so quando o
-- profissional salva pela primeira vez). AnamneseFollowup e um historico
-- append-only: cada edicao gera um evento com data/hora, so os campos que
-- mudaram naquele salvamento (nao duplica os que ficaram iguais) e uma
-- observacao livre opcional -- permite ao profissional acompanhar a
-- evolucao do paciente e consultar informacoes antigas.
create table "Anamnese" (
  id bigint generated by default as identity primary key,
  paciente bigint not null unique references "Paciente"(id) on delete cascade,
  medicacao_em_uso text,
  medico_responsavel text,
  terapia_desde text,
  atendido_desde text,
  queixa_inicial text,
  desenvolvimento_queixa text,
  historico_familiar text,
  tratamento_anterior text,
  uso_substancias text,
  hipotese_diagnostica text,
  expectativas text,
  atualizado_em timestamptz not null default now()
);

-- append-only: a aplicacao nunca faz update/delete aqui, so insert.
create table "AnamneseFollowup" (
  id bigint generated by default as identity primary key,
  anamnese bigint not null references "Anamnese"(id) on delete cascade,
  criado_em timestamptz not null default now(),
  observacao text,
  alteracoes jsonb not null default '[]'::jsonb
);

create index anamnesefollowup_anamnese_idx on "AnamneseFollowup"(anamnese);

alter table "Anamnese" enable row level security;
alter table "AnamneseFollowup" enable row level security;

-- mesmo padrao de PagamentoSessao: sem coluna owner direta, escopo via
-- join ate Paciente.owner.
create policy "anamnese_all_via_paciente" on "Anamnese"
  for all
  using (
    exists (
      select 1 from "Paciente" p
      where p.id = "Anamnese".paciente
        and (p.owner = auth.uid() or public.is_admin())
    )
  )
  with check (
    exists (
      select 1 from "Paciente" p
      where p.id = "Anamnese".paciente
        and (p.owner = auth.uid() or public.is_admin())
    )
  );

create policy "anamnesefollowup_all_via_anamnese" on "AnamneseFollowup"
  for all
  using (
    exists (
      select 1 from "Anamnese" a
      join "Paciente" p on p.id = a.paciente
      where a.id = "AnamneseFollowup".anamnese
        and (p.owner = auth.uid() or public.is_admin())
    )
  )
  with check (
    exists (
      select 1 from "Anamnese" a
      join "Paciente" p on p.id = a.paciente
      where a.id = "AnamneseFollowup".anamnese
        and (p.owner = auth.uid() or public.is_admin())
    )
  );
