-- Migration: sessões recorrentes (Semanal/Quinzenal/Mensal) com renovação
-- automática. Recorrencia guarda a definição da série; Sessao.recorrencia_id
-- marca quais sessões pertencem a qual série (nulo para sessões avulsas).

create table "Recorrencia" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  paciente bigint not null references "Paciente"(id),
  frequencia text not null check (frequencia in ('Semanal', 'Quinzenal', 'Mensal')),
  horario time not null,
  duracao_min numeric not null default 50,
  tipo_sessao text not null,
  data_inicio date not null,
  gerado_ate date not null,
  ativa boolean not null default true,
  cancelada_em timestamptz,
  owner uuid not null default auth.uid()
);

alter table "Sessao"
  add column recorrencia_id bigint references "Recorrencia"(id);

alter table "Recorrencia" enable row level security;

create policy "recorrencia_select_own" on "Recorrencia"
  for select using (owner = auth.uid() or public.is_admin());
create policy "recorrencia_insert_own" on "Recorrencia"
  for insert with check (owner = auth.uid());
create policy "recorrencia_update_own" on "Recorrencia"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "recorrencia_delete_own" on "Recorrencia"
  for delete using (owner = auth.uid() or public.is_admin());
