-- Classificacao Financeira: plano de contas simplificado, uma unica lista
-- de categorias compartilhada entre receitas e despesas (LancamentoFinanceiro
-- ganha uma FK opcional "classificacao"). Pedido explicito do usuario:
-- vincular tanto receitas como despesas a tipos de receita/despesa.
create table "ClassificacaoFinanceira" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  tipo text not null check (tipo in ('Receita', 'Despesa', 'Ambos')),
  owner uuid not null default auth.uid()
);

alter table "LancamentoFinanceiro"
  add column classificacao bigint references "ClassificacaoFinanceira"(id);

alter table "ClassificacaoFinanceira" enable row level security;

create policy "classificacaofinanceira_select_own" on "ClassificacaoFinanceira"
  for select using (owner = auth.uid() or public.is_admin());
create policy "classificacaofinanceira_insert_own" on "ClassificacaoFinanceira"
  for insert with check (owner = auth.uid());
create policy "classificacaofinanceira_update_own" on "ClassificacaoFinanceira"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "classificacaofinanceira_delete_own" on "ClassificacaoFinanceira"
  for delete using (owner = auth.uid() or public.is_admin());
