-- Fila de reenvio de e-mail. Sem policy: so service_role le/escreve,
-- mesmo padrao ja usado em "EventoAssinatura"/"EnvioAutomaticoCarneLeao".
create table "EmailFalhado" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  destinatario text not null,
  assunto text not null,
  corpo_html text not null,
  tentativas int not null default 0,
  proxima_tentativa timestamptz not null default now(),
  resolvido boolean not null default false,
  esgotado boolean not null default false,
  ultimo_erro text
);

alter table "EmailFalhado" enable row level security;
