-- Responsavel financeiro: entidade propria (nao mais um self-FK em
-- Paciente), com vinculo opcional a um Paciente (quando o responsavel
-- tambem e um paciente cadastrado) e N:N com os pacientes pelos quais
-- paga. Substitui o modelo de Paciente.dependente/responsavel_financeiro
-- (dados migrados na migration 20260829000004).
create table "ResponsavelFinanceiro" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  cpf_cnpj text,
  telefone text,
  email text,
  paciente_vinculado bigint references "Paciente"(id),
  owner uuid not null default auth.uid()
);

create table "PacienteResponsavelFinanceiro" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  paciente bigint not null references "Paciente"(id),
  responsavel bigint not null references "ResponsavelFinanceiro"(id),
  owner uuid not null default auth.uid(),
  unique (paciente, responsavel)
);

alter table "ResponsavelFinanceiro" enable row level security;
alter table "PacienteResponsavelFinanceiro" enable row level security;

create policy "responsavelfinanceiro_select_own" on "ResponsavelFinanceiro"
  for select using (owner = auth.uid() or public.is_admin());
create policy "responsavelfinanceiro_insert_own" on "ResponsavelFinanceiro"
  for insert with check (owner = auth.uid());
create policy "responsavelfinanceiro_update_own" on "ResponsavelFinanceiro"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "responsavelfinanceiro_delete_own" on "ResponsavelFinanceiro"
  for delete using (owner = auth.uid() or public.is_admin());

create policy "pacienteresponsavelfinanceiro_select_own" on "PacienteResponsavelFinanceiro"
  for select using (owner = auth.uid() or public.is_admin());
create policy "pacienteresponsavelfinanceiro_insert_own" on "PacienteResponsavelFinanceiro"
  for insert with check (owner = auth.uid());
create policy "pacienteresponsavelfinanceiro_update_own" on "PacienteResponsavelFinanceiro"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "pacienteresponsavelfinanceiro_delete_own" on "PacienteResponsavelFinanceiro"
  for delete using (owner = auth.uid() or public.is_admin());
