-- Despesas recorrentes: mesmo padrao ja usado para sessoes de pacientes
-- (ver 20260729000001_add_recorrencias.sql) -- RecorrenciaDespesa guarda a
-- definicao da serie, LancamentoFinanceiro.recorrencia_despesa_id marca quais
-- lancamentos pertencem a qual serie (nulo para lancamentos avulsos).
create table "RecorrenciaDespesa" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  descricao text not null,
  valor numeric not null,
  classificacao bigint references "ClassificacaoFinanceira"(id),
  conta bigint references "ContaFinanceira"(id),
  frequencia text not null check (frequencia in ('Semanal', 'Quinzenal', 'Mensal')),
  data_inicio date not null,
  gerado_ate date not null,
  ativa boolean not null default true,
  cancelada_em timestamptz,
  owner uuid not null default auth.uid()
);

alter table "LancamentoFinanceiro"
  add column recorrencia_despesa_id bigint references "RecorrenciaDespesa"(id);

alter table "RecorrenciaDespesa" enable row level security;

create policy "recorrenciadespesa_select_own" on "RecorrenciaDespesa"
  for select using (owner = auth.uid() or public.is_admin());
create policy "recorrenciadespesa_insert_own" on "RecorrenciaDespesa"
  for insert with check (owner = auth.uid());
create policy "recorrenciadespesa_update_own" on "RecorrenciaDespesa"
  for update using (owner = auth.uid() or public.is_admin()) with check (owner = auth.uid() or public.is_admin());
create policy "recorrenciadespesa_delete_own" on "RecorrenciaDespesa"
  for delete using (owner = auth.uid() or public.is_admin());
